[dependencies.ethbridge-bridge-events]
features = ["ethers-derive"]
path = "../ethbridge-bridge-events"

[dependencies.ethers]
optional = false
version = "2.0.0"

[features]

[package]
edition = "2021"
name = "ethbridge-events"
version = "0.24.0"
