[package]
name = "ethbridge-bridge-contract"
version = "0.2.0"
edition = "2021"

[dependencies]
ethbridge-bridge-events = { path = "../ethbridge-bridge-events" }
ethbridge-structs = { path = "../ethbridge-structs" }
ethers = "1.0.2"
