
[package]
name = "ethbridge-governance-calls"
version = "0.4.0"
edition = "2021"

[features]


[dependencies]


ethbridge-structs = { path = "../ethbridge-structs", features = ["ethers-derive"] }



ethers = { version = "1.0.2", optional = false }


