
[package]
name = "ethbridge-structs"
version = "0.4.2"
edition = "2021"

[features]

ethers-derive = ["ethers"]


[dependencies]


ethabi = { version = "18.0.0", optional = false }



ethers = { version = "1.0.2", optional = true }


